/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arquinuevo;

import Arquinuevo.presentacion.AsistenciaForm;
import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        // Ejecutar la interfaz gráfica en el hilo de eventos de Swing
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                AsistenciaForm form = new AsistenciaForm();
                form.mostrar();
            }
        });
    }
}
